#Snakefile

IDS, = glob_wildcards("fasta_files/{id}.fa")

rule all:
  input: expand("trees/{id}.tree", id = IDS)
  
rule align:
  input:
    "fasta_files/{id}.fa"
  output:
    "alignments/{id}"
  shell:
    "mafft --auto --thread 8 {input} > {output}"
    
rule tree:
  input:
    "alignments/{id}"
  output:
    "trees/{id}.tree"
  shell:
    "FastTree -quiet -nt {input} > {output}"